### PR TITLE
Danish language added

### PR DESCRIPTION
**Pull request by daviga**
New language added: Danish

### CODE REVIEW

**Comment by markseu** [comment]
Thanks David, do you want me to fix the link in the README?

**Comment by daviga** [comment]
Oh, sorry, I just copied it from the English file and forgot to update. If it's easier for you to do it, yes.
Otherwise, I can fix it.

**Comment by daviga** [comment]
It's already fixed in my version. I can send it over if you want.

**Comment by markseu** [comment]
Awesome, thanks!

**Pull request merged**
