### PR TITLE
Mail encoding and force content in all contact forms

### PR DESCRIPTION
**Pull request by varakh**
As a workaround for the validation of contact form input. Also encoding with german umlauts work now.

### CODE REVIEW

**Comment by markseu** [comment]
It looks like there is no error message if an input field must be entered. Names with Unicode characters still don't work.

**Comment by varakh** [comment]
Yes, it's just your 500 status error. Only message is encoded, not the name.

**Comment by markseu** [comment]
I'm afraid this doesn't work. Right now the contact template does not require to fill out every field. There should be an error text (or other mechanism) that informs the user when input is required.

**Comment by varakh** [comment]
Just a local change on my site to prevent users from spamming. Thought I commit it. :-) 

But anyways, we could at least force html5 validation with required>

**Comment by markseu** [comment]
Thank you @varakh for your effort, appreciate it! My suggestion is to make a new patch, one with different error messages.

**Comment by markseu** [comment]
Thank you @varakh for your effort, appreciate it! 

My suggestion is to make a new patch, one with different error messages:

* new error if form is incomplete
* new text in language.ini to inform the user that form is incomplete
* filter user name in a way that allows Unicode/Umlaut characters (instead of replacing with minus)
* make fields configurable if mandatory or not, to make it adjustable to all needs

What do you think? Help is much appreciated. :smile:

**Comment by varakh** [comment]
Your points sound good. I'll try to implement it, but no ETA, got some other stuff to do today and maybe I'll find some time later.

Making fields configurable for the specific contact form might not be a good idea though. All fields should ALWAYS be mandatory for this case. A validator class might be the way to go here. So we have something to reuse, but this can be a little overdone for this small plugin. ^^

I do think that name filtering should be disabled at all. Just fix the encoding issues. I don't know, but maybe a captcha could be added?! Had them in my last CMS :-).

**Pull request closed without merging**
